version: '3.1'

language: 'id'

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
    analyzer: 'char_wb' # Analisis karakter n-gram
    min_ngram: 1
    max_ngram: 4
  - name: CountVectorsFeaturizer
    analyzer: 'word' # Analisis kata
  - name: DIETClassifier
    epochs: 100 # Jumlah epoch yang digunakan saat pelatihan
    constrain_similarities: True
    loss_type: cross_entropy
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3 # Menangani fallback jika prediksi kurang dari threshold
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
    core_fallback_action_name: 'action_default_fallback'
    core_fallback_threshold: 0.3
    enable_fallback_prediction: true
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
assistant_id: 20241027-171440-broad-goat
